In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import matplotlib 
matplotlib.rcParams["figure.figsize"] = (20,10)

C:\Users\tomde\AppData\Local\Temp\ipykernel_16492\3364595668.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
df = pd.read_csv("final.csv")
df.head()

,Type,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,...,Taylors Lakes,Templestowe,Tullamarine,Vermont South,Wantirna,West Melbourne,Westmeadows,Wheelers Hill,Windsor,Yallambie
0,u,500000,13.5,2,1,1.0,168,86.0,2011,-37.7215,...,False,False,False,False,False,False,False,False,False,False
1,u,515000,13.5,2,1,1.0,141,73.0,2013,-37.7298,...,False,False,False,False,False,False,False,False,False,False
2,u,752000,13.5,3,1,1.0,265,130.0,1993,-37.7302,...,False,False,False,False,False,False,False,False,False,False
3,u,462500,13.5,2,1,1.0,164,126.2,2003,-37.7218,...,False,False,False,False,False,False,False,False,False,False
4,u,510000,13.5,2,1,1.0,141,76.0,1985,-37.7202,...,False,False,False,False,False,False,False,False,False,False

In [3]:
df.shape

(5432, 211)

## Re-sample the dataset

In [4]:
# First, separate the dataframes based on the type
df_h = df[df['Type'] == 'h']
df_u = df[df['Type'] == 'u']
df_t = df[df['Type'] == 't']

# Get the number of 'h' type
num_h = len(df_h)

# Resample 'u' and 't' types
df_u_resampled = df_u.sample(n=num_h, replace=True, random_state=42)
df_t_resampled = df_t.sample(n=num_h, replace=True, random_state=42)

# Concatenate all dataframes
df1 = pd.concat([df_h, df_u_resampled, df_t_resampled])

In [5]:
df1.shape

(13965, 211)

In [6]:
df1.head()

,Type,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,...,Taylors Lakes,Templestowe,Tullamarine,Vermont South,Wantirna,West Melbourne,Westmeadows,Wheelers Hill,Windsor,Yallambie
777,h,1480000,2.5,2,1,1.0,202,151.96765,1964,-37.7996,...,False,False,False,False,False,False,False,False,False,False
778,h,1035000,2.5,2,1,0.0,156,79.00000,1900,-37.8079,...,False,False,False,False,False,False,False,False,False,False
779,h,941000,2.5,2,1,0.0,181,151.96765,1964,-37.8041,...,False,False,False,False,False,False,False,False,False,False
780,h,1876000,2.5,4,2,0.0,245,210.00000,1910,-37.8024,...,False,False,False,False,False,False,False,False,False,False
781,h,1636000,2.5,2,1,2.0,256,107.00000,1890,-37.8060,...,False,False,False,False,False,False,False,False,False,False

## Data cleaning

In [7]:
df1.describe()

,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude
count,1.396500e+04,13965.000000,13965.000000,13965.000000,13965.000000,13965.000000,13965.000000,13965.000000,13965.000000,13965.000000
mean,9.526397e+05,11.410949,2.817043,1.560043,1.593126,329.938059,139.975614,1975.959613,-37.812085,145.007791
std,4.838190e+05,4.755801,0.778615,0.634225,0.772270,202.745841,44.626424,25.561877,0.084057,0.104067
min,1.700000e+05,1.600000,0.000000,0.000000,0.000000,30.000000,1.000000,1854.000000,-38.167620,144.567750
25%,6.500000e+05,8.500000,2.000000,1.000000,1.000000,189.000000,109.000000,1964.000000,-37.874200,144.927730
50%,8.200000e+05,11.200000,3.000000,1.000000,2.000000,257.000000,151.967650,1970.000000,-37.800800,145.024000
75%,1.155000e+06,13.700000,3.000000,2.000000,2.000000,413.000000,151.967650,2000.000000,-37.744400,145.078500
max,6.500000e+06,41.000000,9.000000,8.000000,10.000000,4077.000000,453.000000,2017.000000,-37.560050,145.445300

## Encode

In [8]:
df1.head(2)

,Type,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,...,Taylors Lakes,Templestowe,Tullamarine,Vermont South,Wantirna,West Melbourne,Westmeadows,Wheelers Hill,Windsor,Yallambie
777,h,1480000,2.5,2,1,1.0,202,151.96765,1964,-37.7996,...,False,False,False,False,False,False,False,False,False,False
778,h,1035000,2.5,2,1,0.0,156,79.00000,1900,-37.8079,...,False,False,False,False,False,False,False,False,False,False

In [9]:
dummies = pd.get_dummies(df1.Type)
dummies.head(3)

        h      t      u
777  True  False  False
778  True  False  False
779  True  False  False

In [10]:
df2 = pd.concat([df1,dummies.drop('u',axis='columns')],axis='columns')
df2 = df2.drop('Type',axis='columns')

In [11]:
df2.shape

(13965, 212)

In [12]:
df2.head(2)

,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,...,Tullamarine,Vermont South,Wantirna,West Melbourne,Westmeadows,Wheelers Hill,Windsor,Yallambie,h,t
777,1480000,2.5,2,1,1.0,202,151.96765,1964,-37.7996,144.9984,...,False,False,False,False,False,False,False,False,True,False
778,1035000,2.5,2,1,0.0,156,79.00000,1900,-37.8079,144.9934,...,False,False,False,False,False,False,False,False,True,False

### Re-order the cols

In [13]:
df2_drop = df2.drop(['h', 't', 'Distance', 'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea', 'YearBuilt', 'Lattitude', 'Longtitude'], axis=1)
df2_drop.head(3)

,Price,Airport West,Albion,Alphington,Altona,Altona North,Ascot Vale,Ashburton,Ashwood,Avondale Heights,...,Taylors Lakes,Templestowe,Tullamarine,Vermont South,Wantirna,West Melbourne,Westmeadows,Wheelers Hill,Windsor,Yallambie
777,1480000,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
778,1035000,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
779,941000,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [14]:
# Reindex the DataFrame
df2_reindex = df2.reindex(columns=['Distance','h', 't', 'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea', 'YearBuilt', 'Lattitude', 'Longtitude'])

# Concatenate X_test_reindex and X_test_filtered
df2_reindex = pd.concat([df2_drop, df2_reindex], axis=1)

In [15]:
df2_reindex.head(2)

,Price,Airport West,Albion,Alphington,Altona,Altona North,Ascot Vale,Ashburton,Ashwood,Avondale Heights,...,h,t,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude
777,1480000,False,False,False,False,False,False,False,False,False,...,True,False,2,1,1.0,202,151.96765,1964,-37.7996,144.9984
778,1035000,False,False,False,False,False,False,False,False,False,...,True,False,2,1,0.0,156,79.00000,1900,-37.8079,144.9934

## Model evaluations

In [16]:
X = df2_reindex.drop(['Price'],axis='columns')
y = df2_reindex.Price

In [17]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import ShuffleSplit
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor

def find_best_model_using_gridsearchcv(X,y):
    algos = {
        'linear_regression' : {
            'model': LinearRegression(),
            'params': {}
        },
        'random_forest': {
            'model': RandomForestRegressor(),
            'params' : {
                'n_estimators': [1,5,10,20,30,40]
            }
        },
        'gradient_boosting': {
            'model': GradientBoostingRegressor(),
            'params': {
                'n_estimators': [100, 200],
                'learning_rate': [0.01, 0.1],
            }
        },
        'lasso': {
            'model': Lasso(),
            'params': {
                'alpha': [1,2],
                'selection': ['random', 'cyclic']
            }
        },
        'decision_tree': {
            'model': DecisionTreeRegressor(),
            'params': {
                'criterion' : ['squared_error', 'poisson', 'friedman_mse', 'absolute_error'],
                'splitter': ['best','random']
            }
        }
    }
    scores = []
    cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
    for algo_name, config in algos.items():
        gs =  GridSearchCV(config['model'], config['params'], cv=cv, return_train_score=False, n_jobs=-1)
        gs.fit(X,y)
        scores.append({
            'model': algo_name,
            'best_score': gs.best_score_,
            'best_params': gs.best_params_
        })

    return pd.DataFrame(scores,columns=['model','best_score','best_params'])

find_best_model_using_gridsearchcv(X,y)

               model  best_score                                   best_params
0  linear_regression    0.785541                                            {}
1      random_forest    0.930759                          {'n_estimators': 30}
2  gradient_boosting    0.887534   {'learning_rate': 0.1, 'n_estimators': 200}
3              lasso    0.785523           {'alpha': 1, 'selection': 'cyclic'}
4      decision_tree    0.871718  {'criterion': 'poisson', 'splitter': 'best'}

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=10)

In [19]:
gradient_model = GradientBoostingRegressor(learning_rate=0.1, n_estimators=200)
gradient_model.fit(X_train, y_train)
gradient_model.score(X_test, y_test)

0.8778854626269329

In [20]:
rf_model = RandomForestRegressor(n_estimators=30)
rf_model.fit(X_train, y_train)
rf_model.score(X_test, y_test)

0.9343444322862187

## Testing models

In [21]:
df2_reindex.head(2)

,Price,Airport West,Albion,Alphington,Altona,Altona North,Ascot Vale,Ashburton,Ashwood,Avondale Heights,...,h,t,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude
777,1480000,False,False,False,False,False,False,False,False,False,...,True,False,2,1,1.0,202,151.96765,1964,-37.7996,144.9984
778,1035000,False,False,False,False,False,False,False,False,False,...,True,False,2,1,0.0,156,79.00000,1900,-37.8079,144.9934

In [22]:
def predict_price_g(location,distance,htype,ttype,bedroom2,bathroom,car,landsize,buildingArea,yearBuilt,lattitude,longtitude):    
    loc_index = np.where(X_test.columns==location)[0][0]

    x = np.zeros(len(X_test.columns))
    x[0] = distance
    x[1] = htype
    x[2] = ttype
    x[3] = bedroom2
    x[4] = bathroom
    x[5] = car
    x[6] = landsize
    x[7] = buildingArea
    x[8] = yearBuilt
    x[9] = lattitude
    x[10] = longtitude
    if loc_index >= 0:
        x[loc_index] = 1

    return gradient_model.predict([x])[0]

In [23]:
def predict_price_rf(location,distance,htype,ttype,bedroom2,bathroom,car,landsize,buildingArea,yearBuilt,lattitude,longtitude):    
    loc_index = np.where(X_test.columns==location)[0][0]

    x = np.zeros(len(X_test.columns))
    x[0] = distance
    x[1] = htype
    x[2] = ttype
    x[3] = bedroom2
    x[4] = bathroom
    x[5] = car
    x[6] = landsize
    x[7] = buildingArea
    x[8] = yearBuilt
    x[9] = lattitude
    x[10] = longtitude
    if loc_index >= 0:
        x[loc_index] = 1

    return rf_model.predict([x])[0]

In [24]:
X_test.head(20)

,Airport West,Albion,Alphington,Altona,Altona North,Ascot Vale,Ashburton,Ashwood,Avondale Heights,Balwyn,...,h,t,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude
747,False,False,False,False,False,False,False,False,False,False,...,False,True,3,3,1.0,344,178.00000,2004,-37.79670,144.80830
589,False,False,False,False,False,False,False,False,False,False,...,False,True,3,2,2.0,173,140.00000,2009,-37.83270,145.23480
4175,False,False,False,False,False,False,False,False,False,False,...,True,False,2,1,2.0,468,151.96765,1964,-37.74790,144.99410
658,False,False,False,False,False,False,False,False,False,False,...,False,True,3,3,2.0,248,166.00000,2011,-37.98087,145.06024
4019,False,False,False,False,False,False,False,False,False,False,...,True,False,3,1,2.0,422,132.00000,1950,-37.73370,144.94580
4190,False,False,False,False,False,False,False,False,False,False,...,True,False,3,2,2.0,515,126.00000,1920,-37.74794,144.99111
770,False,False,False,False,False,False,False,False,False,False,...,False,True,3,2,2.0,244,129.00000,2010,-37.82017,144.84904
119,False,False,False,False,False,False,False,False,False,False,...,False,False,2,1,1.0,134,86.40000,1965,-37.89870,145.05570
1083,False,False,False,False,False,False,False,False,True,False,...,True,False,4,2,2.0,573,70.00000,1960,-37.76272,144.85569
530,False,False,False,False,False,False,False,False,False,False,...,False,True,3,2,2.0,219,175.00000,2010,-37.57243,144.92663
557,False,False,False,False,False,False,False,False,False,False,...,False,True,3,2,2.0,239,151.96765,1964,-37.88600,145.28646
772,False,False,False,False,False,False,False,False,False,False,...,False,True,3,2,2.0,314,151.96765,1964,-37.97287,145.01648
313,False,False,False,False,False,False,False,False,False,False,...,False,False,2,1,1.0,133,65.00000,2012,-37.69830,144.99980
124,False,False,False,False,False,False,False,False,False,False,...,False,False,2,2,1.0,225,151.96765,1964,-37.89565,145.02340
337,False,False,False,False,False,False,False,False,False,False,...,False,False,2,1,1.0,235,80.00000,1990,-37.78470,144.81460
699,False,False,False,False,False,False,False,False,False,False,...,False,True,3,2,2.0,220,151.96765,1964,-37.71467,144.91997
686,False,False,False,False,False,False,False,False,False,False,...,False,True,3,2,2.0,224,132.00000,2015,-37.84240,144.86530
126,False,False,False,False,False,False,False,False,False,False,...,False,False,3,2,2.0,235,112.00000,2000,-37.88560,145.09340
36,False,False,False,False,False,False,False,False,False,True,...,False,False,2,1,1.0,115,104.00000,1960,-37.81220,145.08790
208,False,False,False,False,False,False,False,False,False,False,...,False,False,3,2,2.0,189,151.96765,1964,-37.82580,145.04460

### First prediction

In [28]:
df1[(df1['Type'] == 'u') & (df1['Airport West'] == 1)].head(1)

,Type,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,...,Taylors Lakes,Templestowe,Tullamarine,Vermont South,Wantirna,West Melbourne,Westmeadows,Wheelers Hill,Windsor,Yallambie
1,u,515000,13.5,2,1,1.0,141,73.0,2013,-37.7298,...,False,False,False,False,False,False,False,False,False,False

In [29]:
df1.loc[(df1['Type'] == 'u') & (df1['Airport West'] == 1) & (df1['Lattitude'] == -37.7298), 'Longtitude'].head(1)

1    144.8883
Name: Longtitude, dtype: float64

In [30]:
# location,distance,h,t,bedroom2,bathroom,car,landsize,buildingArea,yearBuilt,lattitude,longtitude
predict_price_g("Airport West", 13.5, 0, 0, 2, 1, 1, 141, 73, 2013, -37.7298, 144.8883)

d:\python projects\env\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(

681025.8432547168

In [31]:
predict_price_rf("Airport West", 13.5, 0, 0, 2, 1, 1, 141, 73, 2013, -37.7298, 144.8883)

d:\python projects\env\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

801650.0

### Second prediction

In [32]:
X_test[(X_test['Distance'] == 13.5) & (X_test['Longtitude'] == 144.8083) & (X_test['t'] == 1)].head(1)

,Airport West,Albion,Alphington,Altona,Altona North,Ascot Vale,Ashburton,Ashwood,Avondale Heights,Balwyn,...,h,t,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude
747,False,False,False,False,False,False,False,False,False,False,...,False,True,3,3,1.0,344,178.0,2004,-37.7967,144.8083

In [34]:
# Set the option to display all columns
pd.set_option('display.max_columns', None)

# Display the DataFrame
df2_reindex[(df2_reindex['Distance'] == 13.5) & (df2_reindex['Longtitude'] == 144.8083) & (df2_reindex['t'] == 1)].head(1)

,Price,Airport West,Albion,Alphington,Altona,Altona North,Ascot Vale,Ashburton,Ashwood,Avondale Heights,Balwyn,Balwyn North,Bentleigh,Bentleigh East,Box Hill,Brighton,Brighton East,Brunswick,Brunswick East,Brunswick West,Bulleen,Burwood,Burwood East,Camberwell,Canterbury,Carnegie,Caulfield South,Chadstone,Cheltenham,Clayton,Coburg,Dandenong,Dandenong North,Doncaster,Doncaster East,Donvale,Eaglemont,Elsternwick,Elwood,Epping,Essendon,Essendon North,Fawkner,Footscray,Glen Iris,Glen Waverley,Glenroy,Greensborough,Hadfield,Hampton,Hampton East,Hawthorn,Hawthorn East,Heidelberg,Heidelberg Heights,Highett,Hughesdale,Ivanhoe,Keilor East,Keilor Park,Kew,Kingsbury,Kingsville,Maidstone,Malvern East,Maribyrnong,Mill Park,Mitcham,Moonee Ponds,Moorabbin,Mount Waverley,Murrumbeena,Newport,Niddrie,Northcote,Nunawading,Oak Park,Oakleigh,Oakleigh South,Ormond,Pascoe Vale,Prahran,Preston,Reservoir,Richmond,Ringwood,Ringwood East,Rosanna,Sandringham,South Kingsville,South Yarra,Spotswood,St Kilda,Sunshine,Sunshine West,Surrey Hills,Templestowe Lower,Thomastown,Thornbury,Toorak,Viewbank,Wantirna South,Watsonia,Werribee,West Footscray,Aberfeldie,Armadale,Bayswater,Beaumaris,Braybrook,Bundoora,Coburg North,Collingwood,Craigieburn,Eltham,Essendon West,Ferntree Gully,Heathmont,Kensington,Kew East,Malvern,Mentone,Mont Albert,Mordialloc,Oakleigh East,Parkdale,South Morang,Strathmore,Vermont,Williamstown,Williamstown North,Yarraville,Abbotsford,Albert Park,Balaclava,Bellfield,Berwick,Blackburn,Blackburn North,Blackburn South,Boronia,Broadmeadows,Carlton,Carlton North,Carrum Downs,Caulfield North,Clayton South,Clifton Hill,Cremorne,Croydon,Deer Park,Dingley Village,Eltham North,Fairfield,Fitzroy,Fitzroy North,Flemington,Forest Hill,Frankston,Frankston South,Gladstone Park,Gowanbrae,Greenvale,Heidelberg West,Hillside,Hoppers Crossing,Ivanhoe East,Jacana,Kealba,Keilor Downs,Keysborough,Lalor,Meadow Heights,Melton,Melton South,Middle Park,Montmorency,Mooroolbark,Mulgrave,Noble Park,North Melbourne,Parkville,Point Cook,Port Melbourne,Roxburgh Park,Seaford,Seddon,South Melbourne,St Albans,Sunbury,Sunshine North,Taylors Lakes,Templestowe,Tullamarine,Vermont South,Wantirna,West Melbourne,Westmeadows,Wheelers Hill,Windsor,Yallambie,Distance,h,t,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude
747,450000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,13.5,False,True,3,3,1.0,344,178.0,2004,-37.7967,144.8083

In [35]:
# location,distance,htype, ttype,bedroom2,bathroom,car,landsize,buildingArea,yearBuilt,lattitude,longtitude
predict_price_g("Sunshine West", 13.5, 0, 1, 3, 3, 1, 344, 178, 2004, -37.7967, 144.8083)

d:\python projects\env\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(

604744.8661640092

In [36]:
predict_price_rf("Sunshine West", 13.5, 0, 1, 3, 3, 1, 344, 178, 2004, -37.7967, 144.8083)

d:\python projects\env\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

801650.0

### Create a test csv

In [37]:
X_test.columns

Index(['Airport West', 'Albion', 'Alphington', 'Altona', 'Altona North',
       'Ascot Vale', 'Ashburton', 'Ashwood', 'Avondale Heights', 'Balwyn',
       ...
       'h', 't', 'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea',
       'YearBuilt', 'Lattitude', 'Longtitude'],
      dtype='object', length=211)

In [38]:
X_test_filtered = X_test.drop(['h', 't', 'Distance', 'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea', 'YearBuilt', 'Lattitude', 'Longtitude'], axis=1)
# Replace False values with NaN
X_test_filtered = X_test_filtered.where(X_test_filtered, np.nan)

In [39]:
X_test_filtered

,Airport West,Albion,Alphington,Altona,Altona North,Ascot Vale,Ashburton,Ashwood,Avondale Heights,Balwyn,Balwyn North,Bentleigh,Bentleigh East,Box Hill,Brighton,Brighton East,Brunswick,Brunswick East,Brunswick West,Bulleen,Burwood,Burwood East,Camberwell,Canterbury,Carnegie,Caulfield South,Chadstone,Cheltenham,Clayton,Coburg,Dandenong,Dandenong North,Doncaster,Doncaster East,Donvale,Eaglemont,Elsternwick,Elwood,Epping,Essendon,Essendon North,Fawkner,Footscray,Glen Iris,Glen Waverley,Glenroy,Greensborough,Hadfield,Hampton,Hampton East,Hawthorn,Hawthorn East,Heidelberg,Heidelberg Heights,Highett,Hughesdale,Ivanhoe,Keilor East,Keilor Park,Kew,Kingsbury,Kingsville,Maidstone,Malvern East,Maribyrnong,Mill Park,Mitcham,Moonee Ponds,Moorabbin,Mount Waverley,Murrumbeena,Newport,Niddrie,Northcote,Nunawading,Oak Park,Oakleigh,Oakleigh South,Ormond,Pascoe Vale,Prahran,Preston,Reservoir,Richmond,Ringwood,Ringwood East,Rosanna,Sandringham,South Kingsville,South Yarra,Spotswood,St Kilda,Sunshine,Sunshine West,Surrey Hills,Templestowe Lower,Thomastown,Thornbury,Toorak,Viewbank,Wantirna South,Watsonia,Werribee,West Footscray,Aberfeldie,Armadale,Bayswater,Beaumaris,Braybrook,Bundoora,Coburg North,Collingwood,Craigieburn,Eltham,Essendon West,Ferntree Gully,Heathmont,Kensington,Kew East,Malvern,Mentone,Mont Albert,Mordialloc,Oakleigh East,Parkdale,South Morang,Strathmore,Vermont,Williamstown,Williamstown North,Yarraville,Abbotsford,Albert Park,Balaclava,Bellfield,Berwick,Blackburn,Blackburn North,Blackburn South,Boronia,Broadmeadows,Carlton,Carlton North,Carrum Downs,Caulfield North,Clayton South,Clifton Hill,Cremorne,Croydon,Deer Park,Dingley Village,Eltham North,Fairfield,Fitzroy,Fitzroy North,Flemington,Forest Hill,Frankston,Frankston South,Gladstone Park,Gowanbrae,Greenvale,Heidelberg West,Hillside,Hoppers Crossing,Ivanhoe East,Jacana,Kealba,Keilor Downs,Keysborough,Lalor,Meadow Heights,Melton,Melton South,Middle Park,Montmorency,Mooroolbark,Mulgrave,Noble Park,North Melbourne,Parkville,Point Cook,Port Melbourne,Roxburgh Park,Seaford,Seddon,South Melbourne,St Albans,Sunbury,Sunshine North,Taylors Lakes,Templestowe,Tullamarine,Vermont South,Wantirna,West Melbourne,Westmeadows,Wheelers Hill,Windsor,Yallambie
747,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
589,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
658,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2037,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
# Reindex the DataFrame
X_test_reindex = X_test.reindex(columns=['Distance','h', 't', 'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea', 'YearBuilt', 'Lattitude', 'Longtitude'])

# Concatenate X_test_reindex and X_test_filtered
X_test_reindex = pd.concat([X_test_filtered, X_test_reindex], axis=1)

In [41]:
X_test_reindex

,Airport West,Albion,Alphington,Altona,Altona North,Ascot Vale,Ashburton,Ashwood,Avondale Heights,Balwyn,Balwyn North,Bentleigh,Bentleigh East,Box Hill,Brighton,Brighton East,Brunswick,Brunswick East,Brunswick West,Bulleen,Burwood,Burwood East,Camberwell,Canterbury,Carnegie,Caulfield South,Chadstone,Cheltenham,Clayton,Coburg,Dandenong,Dandenong North,Doncaster,Doncaster East,Donvale,Eaglemont,Elsternwick,Elwood,Epping,Essendon,Essendon North,Fawkner,Footscray,Glen Iris,Glen Waverley,Glenroy,Greensborough,Hadfield,Hampton,Hampton East,Hawthorn,Hawthorn East,Heidelberg,Heidelberg Heights,Highett,Hughesdale,Ivanhoe,Keilor East,Keilor Park,Kew,Kingsbury,Kingsville,Maidstone,Malvern East,Maribyrnong,Mill Park,Mitcham,Moonee Ponds,Moorabbin,Mount Waverley,Murrumbeena,Newport,Niddrie,Northcote,Nunawading,Oak Park,Oakleigh,Oakleigh South,Ormond,Pascoe Vale,Prahran,Preston,Reservoir,Richmond,Ringwood,Ringwood East,Rosanna,Sandringham,South Kingsville,South Yarra,Spotswood,St Kilda,Sunshine,Sunshine West,Surrey Hills,Templestowe Lower,Thomastown,Thornbury,Toorak,Viewbank,Wantirna South,Watsonia,Werribee,West Footscray,Aberfeldie,Armadale,Bayswater,Beaumaris,Braybrook,Bundoora,Coburg North,Collingwood,Craigieburn,Eltham,Essendon West,Ferntree Gully,Heathmont,Kensington,Kew East,Malvern,Mentone,Mont Albert,Mordialloc,Oakleigh East,Parkdale,South Morang,Strathmore,Vermont,Williamstown,Williamstown North,Yarraville,Abbotsford,Albert Park,Balaclava,Bellfield,Berwick,Blackburn,Blackburn North,Blackburn South,Boronia,Broadmeadows,Carlton,Carlton North,Carrum Downs,Caulfield North,Clayton South,Clifton Hill,Cremorne,Croydon,Deer Park,Dingley Village,Eltham North,Fairfield,Fitzroy,Fitzroy North,Flemington,Forest Hill,Frankston,Frankston South,Gladstone Park,Gowanbrae,Greenvale,Heidelberg West,Hillside,Hoppers Crossing,Ivanhoe East,Jacana,Kealba,Keilor Downs,Keysborough,Lalor,Meadow Heights,Melton,Melton South,Middle Park,Montmorency,Mooroolbark,Mulgrave,Noble Park,North Melbourne,Parkville,Point Cook,Port Melbourne,Roxburgh Park,Seaford,Seddon,South Melbourne,St Albans,Sunbury,Sunshine North,Taylors Lakes,Templestowe,Tullamarine,Vermont South,Wantirna,West Melbourne,Westmeadows,Wheelers Hill,Windsor,Yallambie,Distance,h,t,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude
747,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.5,False,True,3,3,1.0,344,178.00000,2004,-37.79670,144.80830
589,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.3,False,True,3,2,2.0,173,140.00000,2009,-37.83270,145.23480
4175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.8,True,False,2,1,2.0,468,151.96765,1964,-37.74790,144.99410
658,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,False,True,3,3,2.0,248,166.00000,2011,-37.98087,145.06024
4019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.9,True,False,3,1,2.0,422,132.00000,1950,-37.73370,144.94580
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.7,True,False,4,2,2.0,604,151.96765,1964,-37.73975,144.96510
97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.2,False,False,3,1,1.0,138,76.80000,1970,-37.75904,144.93388
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.7,False,False,2,1,1.0,134,76.80000,1970,-37.79541,145.06570
2037,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.7,True,False,3,1,3.0,533,150.00000,1960,-37.72631,144.96274
431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.4,False,True,3,3,2.0,307,177.00000,2014,-37.91648,145.04927

In [42]:
X_test_reindex.to_csv('X_test.csv', index=False)

### Compare result to csv

In [72]:
X_test_reindex.head()

,Airport West,Albion,Alphington,Altona,Altona North,Ascot Vale,Ashburton,Ashwood,Avondale Heights,Balwyn,Balwyn North,Bentleigh,Bentleigh East,Box Hill,Brighton,Brighton East,Brunswick,Brunswick East,Brunswick West,Bulleen,Burwood,Burwood East,Camberwell,Canterbury,Carnegie,Caulfield South,Chadstone,Cheltenham,Clayton,Coburg,Dandenong,Dandenong North,Doncaster,Doncaster East,Donvale,Eaglemont,Elsternwick,Elwood,Epping,Essendon,Essendon North,Fawkner,Footscray,Glen Iris,Glen Waverley,Glenroy,Greensborough,Hadfield,Hampton,Hampton East,Hawthorn,Hawthorn East,Heidelberg,Heidelberg Heights,Highett,Hughesdale,Ivanhoe,Keilor East,Keilor Park,Kew,Kingsbury,Kingsville,Maidstone,Malvern East,Maribyrnong,Mill Park,Mitcham,Moonee Ponds,Moorabbin,Mount Waverley,Murrumbeena,Newport,Niddrie,Northcote,Nunawading,Oak Park,Oakleigh,Oakleigh South,Ormond,Pascoe Vale,Prahran,Preston,Reservoir,Richmond,Ringwood,Ringwood East,Rosanna,Sandringham,South Kingsville,South Yarra,Spotswood,St Kilda,Sunshine,Sunshine West,Surrey Hills,Templestowe Lower,Thomastown,Thornbury,Toorak,Viewbank,Wantirna South,Watsonia,Werribee,West Footscray,Aberfeldie,Armadale,Bayswater,Beaumaris,Braybrook,Bundoora,Coburg North,Collingwood,Craigieburn,Eltham,Essendon West,Ferntree Gully,Heathmont,Kensington,Kew East,Malvern,Mentone,Mont Albert,Mordialloc,Oakleigh East,Parkdale,South Morang,Strathmore,Vermont,Williamstown,Williamstown North,Yarraville,Abbotsford,Albert Park,Balaclava,Bellfield,Berwick,Blackburn,Blackburn North,Blackburn South,Boronia,Broadmeadows,Carlton,Carlton North,Carrum Downs,Caulfield North,Clayton South,Clifton Hill,Cremorne,Croydon,Deer Park,Dingley Village,Eltham North,Fairfield,Fitzroy,Fitzroy North,Flemington,Forest Hill,Frankston,Frankston South,Gladstone Park,Gowanbrae,Greenvale,Heidelberg West,Hillside,Hoppers Crossing,Ivanhoe East,Jacana,Kealba,Keilor Downs,Keysborough,Lalor,Meadow Heights,Melton,Melton South,Middle Park,Montmorency,Mooroolbark,Mulgrave,Noble Park,North Melbourne,Parkville,Point Cook,Port Melbourne,Roxburgh Park,Seaford,Seddon,South Melbourne,St Albans,Sunbury,Sunshine North,Taylors Lakes,Templestowe,Tullamarine,Vermont South,Wantirna,West Melbourne,Westmeadows,Wheelers Hill,Windsor,Yallambie,Distance,h,t,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude
747,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.5,False,True,3,3,1.0,344,178.00000,2004,-37.79670,144.80830
589,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.3,False,True,3,2,2.0,173,140.00000,2009,-37.83270,145.23480
4175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.8,True,False,2,1,2.0,468,151.96765,1964,-37.74790,144.99410
658,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,False,True,3,3,2.0,248,166.00000,2011,-37.98087,145.06024
4019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.9,True,False,3,1,2.0,422,132.00000,1950,-37.73370,144.94580

In [74]:
df2_reindex[(df2_reindex['Heathmont'] == 1) & (df2_reindex['Distance'] == 21.3) & (df2_reindex['Longtitude'] == 145.23480) & (df2_reindex['t'] == 1)].head(1)

,Price,Airport West,Albion,Alphington,Altona,Altona North,Ascot Vale,Ashburton,Ashwood,Avondale Heights,Balwyn,Balwyn North,Bentleigh,Bentleigh East,Box Hill,Brighton,Brighton East,Brunswick,Brunswick East,Brunswick West,Bulleen,Burwood,Burwood East,Camberwell,Canterbury,Carnegie,Caulfield South,Chadstone,Cheltenham,Clayton,Coburg,Dandenong,Dandenong North,Doncaster,Doncaster East,Donvale,Eaglemont,Elsternwick,Elwood,Epping,Essendon,Essendon North,Fawkner,Footscray,Glen Iris,Glen Waverley,Glenroy,Greensborough,Hadfield,Hampton,Hampton East,Hawthorn,Hawthorn East,Heidelberg,Heidelberg Heights,Highett,Hughesdale,Ivanhoe,Keilor East,Keilor Park,Kew,Kingsbury,Kingsville,Maidstone,Malvern East,Maribyrnong,Mill Park,Mitcham,Moonee Ponds,Moorabbin,Mount Waverley,Murrumbeena,Newport,Niddrie,Northcote,Nunawading,Oak Park,Oakleigh,Oakleigh South,Ormond,Pascoe Vale,Prahran,Preston,Reservoir,Richmond,Ringwood,Ringwood East,Rosanna,Sandringham,South Kingsville,South Yarra,Spotswood,St Kilda,Sunshine,Sunshine West,Surrey Hills,Templestowe Lower,Thomastown,Thornbury,Toorak,Viewbank,Wantirna South,Watsonia,Werribee,West Footscray,Aberfeldie,Armadale,Bayswater,Beaumaris,Braybrook,Bundoora,Coburg North,Collingwood,Craigieburn,Eltham,Essendon West,Ferntree Gully,Heathmont,Kensington,Kew East,Malvern,Mentone,Mont Albert,Mordialloc,Oakleigh East,Parkdale,South Morang,Strathmore,Vermont,Williamstown,Williamstown North,Yarraville,Abbotsford,Albert Park,Balaclava,Bellfield,Berwick,Blackburn,Blackburn North,Blackburn South,Boronia,Broadmeadows,Carlton,Carlton North,Carrum Downs,Caulfield North,Clayton South,Clifton Hill,Cremorne,Croydon,Deer Park,Dingley Village,Eltham North,Fairfield,Fitzroy,Fitzroy North,Flemington,Forest Hill,Frankston,Frankston South,Gladstone Park,Gowanbrae,Greenvale,Heidelberg West,Hillside,Hoppers Crossing,Ivanhoe East,Jacana,Kealba,Keilor Downs,Keysborough,Lalor,Meadow Heights,Melton,Melton South,Middle Park,Montmorency,Mooroolbark,Mulgrave,Noble Park,North Melbourne,Parkville,Point Cook,Port Melbourne,Roxburgh Park,Seaford,Seddon,South Melbourne,St Albans,Sunbury,Sunshine North,Taylors Lakes,Templestowe,Tullamarine,Vermont South,Wantirna,West Melbourne,Westmeadows,Wheelers Hill,Windsor,Yallambie,Distance,h,t,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude
589,701000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,21.3,False,True,3,2,2.0,173,140.0,2009,-37.8327,145.2348

In [75]:
predict_price_rf("Heathmont", 13.5, 0, 1, 3, 2, 2, 173, 140, 2009, 	-37.83270, 145.23480)

d:\python projects\env\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

801650.0

In [76]:
predict_price_g("Heathmont", 13.5, 0, 1, 3, 2, 2, 173, 140, 2009, -37.83270, 145.23480)

d:\python projects\env\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(

681025.8432547168

In [85]:
df2_reindex[(df2_reindex['Mentone'] == 1) & (df2_reindex['Distance'] == 20) & (df2_reindex['BuildingArea'] == 166)].head(1)

,Price,Airport West,Albion,Alphington,Altona,Altona North,Ascot Vale,Ashburton,Ashwood,Avondale Heights,Balwyn,Balwyn North,Bentleigh,Bentleigh East,Box Hill,Brighton,Brighton East,Brunswick,Brunswick East,Brunswick West,Bulleen,Burwood,Burwood East,Camberwell,Canterbury,Carnegie,Caulfield South,Chadstone,Cheltenham,Clayton,Coburg,Dandenong,Dandenong North,Doncaster,Doncaster East,Donvale,Eaglemont,Elsternwick,Elwood,Epping,Essendon,Essendon North,Fawkner,Footscray,Glen Iris,Glen Waverley,Glenroy,Greensborough,Hadfield,Hampton,Hampton East,Hawthorn,Hawthorn East,Heidelberg,Heidelberg Heights,Highett,Hughesdale,Ivanhoe,Keilor East,Keilor Park,Kew,Kingsbury,Kingsville,Maidstone,Malvern East,Maribyrnong,Mill Park,Mitcham,Moonee Ponds,Moorabbin,Mount Waverley,Murrumbeena,Newport,Niddrie,Northcote,Nunawading,Oak Park,Oakleigh,Oakleigh South,Ormond,Pascoe Vale,Prahran,Preston,Reservoir,Richmond,Ringwood,Ringwood East,Rosanna,Sandringham,South Kingsville,South Yarra,Spotswood,St Kilda,Sunshine,Sunshine West,Surrey Hills,Templestowe Lower,Thomastown,Thornbury,Toorak,Viewbank,Wantirna South,Watsonia,Werribee,West Footscray,Aberfeldie,Armadale,Bayswater,Beaumaris,Braybrook,Bundoora,Coburg North,Collingwood,Craigieburn,Eltham,Essendon West,Ferntree Gully,Heathmont,Kensington,Kew East,Malvern,Mentone,Mont Albert,Mordialloc,Oakleigh East,Parkdale,South Morang,Strathmore,Vermont,Williamstown,Williamstown North,Yarraville,Abbotsford,Albert Park,Balaclava,Bellfield,Berwick,Blackburn,Blackburn North,Blackburn South,Boronia,Broadmeadows,Carlton,Carlton North,Carrum Downs,Caulfield North,Clayton South,Clifton Hill,Cremorne,Croydon,Deer Park,Dingley Village,Eltham North,Fairfield,Fitzroy,Fitzroy North,Flemington,Forest Hill,Frankston,Frankston South,Gladstone Park,Gowanbrae,Greenvale,Heidelberg West,Hillside,Hoppers Crossing,Ivanhoe East,Jacana,Kealba,Keilor Downs,Keysborough,Lalor,Meadow Heights,Melton,Melton South,Middle Park,Montmorency,Mooroolbark,Mulgrave,Noble Park,North Melbourne,Parkville,Point Cook,Port Melbourne,Roxburgh Park,Seaford,Seddon,South Melbourne,St Albans,Sunbury,Sunshine North,Taylors Lakes,Templestowe,Tullamarine,Vermont South,Wantirna,West Melbourne,Westmeadows,Wheelers Hill,Windsor,Yallambie,Distance,h,t,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude
658,995000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,20.0,False,True,3,3,2.0,248,166.0,2011,-37.98087,145.06024

In [86]:
predict_price_rf("Mentone", 20, 0, 1, 3, 3, 2, 248, 166, 2011, -37.98087, 145.06024)

d:\python projects\env\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

801650.0

In [87]:
predict_price_g("Mentone", 20, 0, 1, 3, 3, 2, 248, 166, 2011, -37.98087, 145.06024)

d:\python projects\env\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(

681025.8432547168

# Exporting model

In [88]:
import joblib

# Export the rf_model
joblib.dump(rf_model, 'rf_model.pkl')

['rf_model.pkl']